=== FOREVEREALIZE/zyp-anime-db/schemas/season.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.gihtubusercontent.com/foreverealize/zyp-anime-db/main/schemas/season.schema.json",
    "title": "Season",
    "description": "A Season within the Zyp Database",
    "type": "object",
    "properties": {
        "id": {
            "description": "ID of the Season. Usually the lowercase anime name without special characters and all spaces replaced with dashes with the season number at the end.\nMust be unique.",
            "type": "string"
        },
        "number": {
            "description": "The number or position of the Season within it's Anime.",
            "type": "number"
        },
        "name": {
            "description": "The translated (non-romanized) English name of the Season. If none exists, the format \"{Anime Name}: Season {Season Number}\" may be used.",
            "type": "string"
        },
        "releaseStart": {
            "description": "The Date (and maybe Time) in the ZDB Date / DateTime Format in which the release of this Season started. \"UNKNOWN\" if the Season is not releasing yet.",
            "type": "string"
        },
        "releaseEnd": {
            "description": "The Date (and maybe Time) in the ZDB Date / DateTime Format in which the release of this Season ended. \"UNKNOWN\" if the Season is still releasing.",
            "type": "string"
        },
        "episodes": {
            "description": "A list of the IDs of all the Episodes of this Season.",
            "type": "array",
            "items": {
                "type": "string"
            },
            "uniqueItems": true
        }
    },
    "required": ["id", "number", "name", "releaseStart", "releaseEnd", "episodes"]
}

=== FOREVEREALIZE/zyp-anime-db/Season/haikyuu-2.json
{
    "$schema": "https://raw.githubusercontent.com/foreverealize/zyp-anime-db/main/schemas/season.schema.json",
    "id": "haikyuu-2",
    "number": 2,
    "name": "Haikyuu!!: Season 2",
    "releaseStart": "2015-10-04",
    "releaseEnd": "2016-03-27",
    "episodes": [
        "haikyuu-2-1",
        "haikyuu-2-2",
        "haikyuu-2-3",
        "haikyuu-2-4",
        "haikyuu-2-5",
        "haikyuu-2-6",
        "haikyuu-2-7",
        "haikyuu-2-8",
        "haikyuu-2-9",
        "haikyuu-2-10",
        "haikyuu-2-11",
        "haikyuu-2-12",
        "haikyuu-2-13",
        "haikyuu-2-14",
        "haikyuu-2-15",
        "haikyuu-2-16",
        "haikyuu-2-17",
        "haikyuu-2-18",
        "haikyuu-2-19",
        "haikyuu-2-20",
        "haikyuu-2-21",
        "haikyuu-2-22",
        "haikyuu-2-23",
        "haikyuu-2-24",
        "haikyuu-2-25"
    ]
}

=== FOREVEREALIZE/zyp-anime-db/Season/horimiya-1.json
{
    "$schema": "https://raw.githubusercontent.com/foreverealize/zyp-anime-db/main/schemas/season.schema.json",
    "id": "horimiya-1",
    "number": 1,
    "name": "Horimiya: Season 1",
    "releaseStart": "2021-01-10",
    "releaseEnd": "2021-04-04",
    "episodes": [
        "horimiya-1-1",
        "horimiya-1-2",
        "horimiya-1-3",
        "horimiya-1-4",
        "horimiya-1-5",
        "horimiya-1-6",
        "horimiya-1-7",
        "horimiya-1-8",
        "horimiya-1-9",
        "horimiya-1-10",
        "horimiya-1-11",
        "horimiya-1-12",
        "horimiya-1-13"
    ]
}

=== FOREVEREALIZE/zyp-anime-db/Season/haikyuu-5.json
{
    "$schema": "https://raw.githubusercontent.com/foreverealize/zyp-anime-db/main/schemas/season.schema.json",
    "id": "haikyuu-5",
    "number": 5,
    "name": "Haikyuu!! To the Top Part 2",
    "releaseStart": "2020-10-03",
    "releaseEnd": "2020-12-19",
    "episodes": [
        "haikyuu-5-1",
        "haikyuu-5-2",
        "haikyuu-5-3",
        "haikyuu-5-4",
        "haikyuu-5-5",
        "haikyuu-5-6",
        "haikyuu-5-7",
        "haikyuu-5-8",
        "haikyuu-5-9",
        "haikyuu-5-10",
        "haikyuu-5-11",
        "haikyuu-5-12"
    ]
}

=== FOREVEREALIZE/zyp-anime-db/Season/danganronpa-1.json
{
    "$schema": "https://raw.githubusercontent.com/foreverealize/zyp-anime-db/main/schemas/season.schema.json",
    "id": "danganronpa-1",
    "number": 1,
    "name": "Danganronpa: Season 1",
    "releaseStart": "2013-06-05",
    "releaseEnd": "2013-09-27",
    "episodes": [
        "danganronpa-1-1",
        "danganronpa-1-2",
        "danganronpa-1-3",
        "danganronpa-1-4",
        "danganronpa-1-5",
        "danganronpa-1-6",
        "danganronpa-1-7",
        "danganronpa-1-8",
        "danganronpa-1-9",
        "danganronpa-1-10",
        "danganronpa-1-11",
        "danganronpa-1-12",
        "danganronpa-1-13"
    ]
}

=== FOREVEREALIZE/zyp-anime-db/Season/given-1.json
{
    "$schema": "https://raw.githubusercontent.com/foreverealize/zyp-anime-db/main/schemas/season.schema.json",
    "id": "given-1",
    "number": 1,
    "name": "Given: Season 1",
    "releaseStart": "2019-07-12",
    "releaseEnd": "2019-09-20",
    "episodes": [
        "given-1-1",
        "given-1-2",
        "given-1-3",
        "given-1-4",
        "given-1-5",
        "given-1-6",
        "given-1-7",
        "given-1-8",
        "given-1-9",
        "given-1-10",
        "given-1-11"
    ]
}

=== FOREVEREALIZE/zyp-anime-db/Season/school-babysitters-1.json
{
    "$schema": "https://raw.githubusercontent.com/foreverealize/zyp-anime-db/main/schemas/season.schema.json",
    "id": "school-babysitters-1",
    "number": 1,
    "name": "School Babysitters: Season 1",
    "releaseStart": "2018-01-07",
    "releaseEnd": "2018-03-25",
    "episodes": [
        "school-babysitters-1-1",
        "school-babysitters-1-2",
        "school-babysitters-1-3",
        "school-babysitters-1-4",
        "school-babysitters-1-5",
        "school-babysitters-1-6",
        "school-babysitters-1-7",
        "school-babysitters-1-8",
        "school-babysitters-1-9",
        "school-babysitters-1-10",
        "school-babysitters-1-11",
        "school-babysitters-1-12"
    ]
}

=== FOREVEREALIZE/zyp-anime-db/Season/bungou-stray-dogs-4.json
{
    "$schema": "https://raw.githubusercontent.com/foreverealize/zyp-anime-db/main/schemas/season.schema.json",
    "id": "bungou-stray-dogs-4",
    "number": 4,
    "name": "Bungou Stray Dogs: Season 4",
    "releaseStart": "2023-01-04",
    "releaseEnd": "2023-03-29",
    "episodes": [
        "bungou-stray-dogs-4-1",
        "bungou-stray-dogs-4-2",
        "bungou-stray-dogs-4-3",
        "bungou-stray-dogs-4-4",
        "bungou-stray-dogs-4-5",
        "bungou-stray-dogs-4-6",
        "bungou-stray-dogs-4-7",
        "bungou-stray-dogs-4-8",
        "bungou-stray-dogs-4-9",
        "bungou-stray-dogs-4-10",
        "bungou-stray-dogs-4-11",
        "bungou-stray-dogs-4-12",
        "bungou-stray-dogs-4-13"
    ]
}

=== FOREVEREALIZE/zyp-anime-db/Season/sasaki-and-miyano-1.json
{
    "$schema": "https://raw.githubusercontent.com/foreverealize/zyp-anime-db/main/schemas/season.schema.json",
    "id": "sasaki-and-miyano-1",
    "number": 1,
    "name": "Sasaki and Miyano: Season 1",
    "releaseStart": "2022-01-10",
    "releaseEnd": "2022-03-28",
    "episodes": [
        "sasaki-and-miyano-1-1",
        "sasaki-and-miyano-1-2",
        "sasaki-and-miyano-1-3",
        "sasaki-and-miyano-1-4",
        "sasaki-and-miyano-1-5",
        "sasaki-and-miyano-1-6",
        "sasaki-and-miyano-1-7",
        "sasaki-and-miyano-1-8",
        "sasaki-and-miyano-1-9",
        "sasaki-and-miyano-1-10",
        "sasaki-and-miyano-1-11",
        "sasaki-and-miyano-1-12"
    ]
}
