=== FOREVEREALIZE/zyp-anime-db/schemas/season.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.gihtubusercontent.com/foreverealize/zyp-anime-db/main/schemas/season.schema.json",
    "title": "Season",
    "description": "A Season within the Zyp Database",
    "type": "object",
    "properties": {
        "id": {
            "description": "ID of the Season. Usually the lowercase anime name without special characters and all spaces replaced with dashes with the season number at the end.\nMust be unique.",
            "type": "string"
        },
        "number": {
            "description": "The number or position of the Season within it's Anime.",
            "type": "number"
        },
        "name": {
            "description": "The translated (non-romanized) English name of the Season. If none exists, the format \"{Anime Name}: Season {Season Number}\" may be used.",
            "type": "string"
        },
        "releaseStart": {
            "description": "The Date (and maybe Time) in the ZDB Date / DateTime Format in which the release of this Season started. \"UNKNOWN\" if the Season is not releasing yet.",
            "type": "string"
        },
        "releaseEnd": {
            "description": "The Date (and maybe Time) in the ZDB Date / DateTime Format in which the release of this Season ended. \"UNKNOWN\" if the Season is still releasing.",
            "type": "string"
        },
        "episodes": {
            "description": "A list of the IDs of all the Episodes of this Season.",
            "type": "array",
            "items": {
                "type": "string"
            },
            "uniqueItems": true
        }
    },
    "required": ["id", "number", "name", "releaseStart", "releaseEnd", "episodes"]
}

=== FOREVEREALIZE/zyp-anime-db/Season/haikyuu-3.json
{
    "$schema": "https://raw.githubusercontent.com/foreverealize/zyp-anime-db/main/schemas/season.schema.json",
    "id": "haikyuu-3",
    "number": 3,
    "name": "Haikyuu!! Karasuno High vs Shiratorizawa Academy",
    "releaseStart": "2016-10-08",
    "releaseEnd": "2016-12-10",
    "episodes": [
        "haikyuu-3-1",
        "haikyuu-3-2",
        "haikyuu-3-3",
        "haikyuu-3-4",
        "haikyuu-3-5",
        "haikyuu-3-6",
        "haikyuu-3-7",
        "haikyuu-3-8",
        "haikyuu-3-9",
        "haikyuu-3-10"
    ]
}

=== FOREVEREALIZE/zyp-anime-db/Season/noragami-1.json
{
    "$schema": "https://raw.githubusercontent.com/foreverealize/zyp-anime-db/main/schemas/season.schema.json",
    "id": "noragami-1",
    "number": 1,
    "name": "Noragami: Season 1",
    "releaseStart": "2014-01-05",
    "releaseEnd": "2014-03-23",
    "episodes": [
        "noragami-1-1",
        "noragami-1-2",
        "noragami-1-3",
        "noragami-1-4",
        "noragami-1-5",
        "noragami-1-6",
        "noragami-1-7",
        "noragami-1-8",
        "noragami-1-9",
        "noragami-1-10",
        "noragami-1-11",
        "noragami-1-12"
    ]
}

=== FOREVEREALIZE/zyp-anime-db/Season/neon-genesis-evangelion-1.json
{
    "$schema": "https://raw.githubusercontent.com/foreverealize/zyp-anime-db/main/schemas/season.schema.json",
    "id": "neon-genesis-evangelion-1",
    "number": 1,
    "name": "Neon Genesis Evangelion: Season 1",
    "releaseStart": "1995-10-04",
    "releaseEnd": "1996-03-27",
    "episodes": [
        "neon-genesis-evangelion-1-1",
        "neon-genesis-evangelion-1-2",
        "neon-genesis-evangelion-1-3",
        "neon-genesis-evangelion-1-4",
        "neon-genesis-evangelion-1-5",
        "neon-genesis-evangelion-1-6",
        "neon-genesis-evangelion-1-7",
        "neon-genesis-evangelion-1-8",
        "neon-genesis-evangelion-1-9",
        "neon-genesis-evangelion-1-10",
        "neon-genesis-evangelion-1-11",
        "neon-genesis-evangelion-1-12",
        "neon-genesis-evangelion-1-13",
        "neon-genesis-evangelion-1-14",
        "neon-genesis-evangelion-1-15",
        "neon-genesis-evangelion-1-16",
        "neon-genesis-evangelion-1-17",
        "neon-genesis-evangelion-1-18",
        "neon-genesis-evangelion-1-19",
        "neon-genesis-evangelion-1-20",
        "neon-genesis-evangelion-1-21",
        "neon-genesis-evangelion-1-22",
        "neon-genesis-evangelion-1-23",
        "neon-genesis-evangelion-1-24",
        "neon-genesis-evangelion-1-25",
        "neon-genesis-evangelion-1-26"
    ]
}
